const VUE_APP_SINGLEBOARD_MODE = !!parseInt(process.env.VUE_APP_SINGLEBOARD_MODE)
const VUE_APP_SINGLEBOARD_SLUG = process.env.VUE_APP_SINGLEBOARD_SLUG || '_'
const VUE_APP_LOCALSTORAGE_KEY_PREFIX = process.env.VUE_APP_LOCALSTORAGE_KEY_PREFIX || 'OurShoppingList_'

export {
  VUE_APP_LOCALSTORAGE_KEY_PREFIX,
  VUE_APP_SINGLEBOARD_MODE,
  VUE_APP_SINGLEBOARD_SLUG,
}
