const VUE_APP_DISABLE_CONTEXTMENU = !!parseInt(process.env.VUE_APP_DISABLE_CONTEXTMENU)
const VUE_APP_I18N_FALLBACK_LOCALE = process.env.VUE_APP_I18N_FALLBACK_LOCALE || 'en'
const VUE_APP_I18N_FORCE_LOCALE = !!parseInt(process.env.VUE_APP_I18N_FORCE_LOCALE)
const VUE_APP_I18N_LOCALE = process.env.VUE_APP_I18N_LOCALE || 'en'
const VUE_APP_LOCALSTORAGE_KEY_PREFIX = process.env.VUE_APP_LOCALSTORAGE_KEY_PREFIX || 'OurShoppingList_'
const VUE_APP_SINGLEBOARD_ID = process.env.VUE_APP_SINGLEBOARD_ID || '00000000-0000-0000-0000-000000000000'
const VUE_APP_SINGLEBOARD_MODE = !!parseInt(process.env.VUE_APP_SINGLEBOARD_MODE)
const VUE_APP_SINGLEBOARD_SLUG = process.env.VUE_APP_SINGLEBOARD_SLUG || '_'

module.exports = {
  VUE_APP_DISABLE_CONTEXTMENU,
  VUE_APP_I18N_FALLBACK_LOCALE,
  VUE_APP_I18N_FORCE_LOCALE,
  VUE_APP_I18N_LOCALE,
  VUE_APP_LOCALSTORAGE_KEY_PREFIX,
  VUE_APP_SINGLEBOARD_ID,
  VUE_APP_SINGLEBOARD_MODE,
  VUE_APP_SINGLEBOARD_SLUG,
}
